User creation
BoulinguezTheo/campus_hotel_artichaut_frontend pull request #18
Opened 2023-11-28 15:10 UTC by azarual01

2023-11-28 15:15 UTC, ludovicpeysson9 approved these changes

2023-11-28 15:35 UTC, BoulinguezTheo requested changes

2023-11-28 15:35 UTC, BoulinguezTheo commented on lib/main.dart
> +      initialLocation: ConstantsApp.INSCRIPTION_ROUTE,
La route d'initialisation reste la homepage à la demande du client

2023-11-28 15:35 UTC, BoulinguezTheo commented on lib/theme/theme.dart
> +    error: Color.fromRGBO(235, 52, 52, 1),
Nice, bien vu 👍

2023-11-28 15:35 UTC, BoulinguezTheo commented on lib/utils/large_cta_button.dart
> +                fontSize: 24, color: Color.fromRGBO(255, 255, 255, 1)),
Pourquoi tu n'utilises pas le theme ?

2023-11-28 15:35 UTC, BoulinguezTheo commented on lib/views/main_pages/inscription.dart
> +                enableSuggestions: false),
Tous tes inputs ont le même validator, à savoir qu'ils ne soient pas vides. C'est pas ce que l'on souhaite.
Pour le mail on veut vérifier que c'est bien un email, pour le mot de passe qu'il fasse plus 8 caractères.

2023-11-29 08:21 UTC, ludovicpeysson9 requested changes

2023-11-29 08:21 UTC, ludovicpeysson9 commented on lib/main.dart
Pourquoi cette fonction void onPressed (l27) dans main.dart?

2023-11-29 08:28 UTC, ludovicpeysson9 approved these changes

2023-11-29 08:45 UTC, BoulinguezTheo commented on lib/main.dart
Bonne question

2023-11-29 08:46 UTC, BoulinguezTheo approved these changes

2023-11-29 08:46 UTC, merged